var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "xxxxxxxxxxxxx              o                                                    ",
   "x           x          x   x    x                *y                             ",
   "x        o  x           x!!!!!!x               yyyy                             ",
   "x        o  x            xxxxxx                         #                       ",
   "x o      o  x     x                                                             ",
   "x o         x                         o                xx       x               ",
   "x o      xxxxxxx                                    x!!!!!!!x    x              ",
   "x o                               x       x         x!x v x!x     x             ",
   "x o                              x         x        x!x   x!x                 o ",
   "x                    xx         x           x       xxx   xxx                   ",
   "xxxx                           x             x                               xxx",
   "x                                                                           #x  ",
   "x                         o                            o          x         =x  ",
   "x    @      x$                                                    x   xxxxxxxx  ",
   "xxxxxxxxx   xxxxxxx      xxx      xxxxxxxxxxxxxxxxxxxx     xxxxxxxx!!!x         ",
   "       x!!!!!x    x!!!!!!!!!!!!!!!x                  x     x      xxxxx         ",
   "       xxxxxxx    x!!!!!!!!!!!!!!!x                  xy   yx                    ",
   "                  x!!!!!!!!!!!!!!!x                  x!!!!!x                    ",
   "                  xxxxxxxxxxxxxxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                                ",
    "                                                                                ",
    "                             o                                                  ",
    "                                                                                ",
    "                 x    xx     x    xx    x                                       ",
    "                 x!!!x  x!!!!!!!!x  x!!!x                                       ",
    "                 xxvxx  xxxvxxxxxx  xxvxx                                       ",
    "             x                                                                  ",
    "                                                                                ",
    "                                                     xxxxxx                     ",
    "        o                                            x!!!!x                     ",
    "                                               o    xx  v x    x                ",
    "      xxxxxx                                         x    x!!!!x                ",
    "      x!!!!x                                    x   =x    x!!!!x             x  ",
    "      x    x                             x=     x!!!!x o  xxxxxx       x     x  ",
    "      x    x    #                        x!!!!!!!!!!!x                 x!!!!!x  ",
    "  @   x    x$            o        xxxxxxxxxxxxxxxxxxxx            x    xxxxxxx  ",
    "  xxxxx o  xxxxxxxx               x                  x     xxxxxxxx!!!x         ",
    "                                          o          x     x      xxxxx   o     ",
    "                         #                           xy   yx  o           o     ",
    "                                                     x!!!!!x  o  o  o   o o     ",
    "                 $xxxxxxxxxxxxxxxxx                  xxxxxxx*                   ",
    "xxxx|  xxxx | xxxx                    xxx  = xxx            xxxxx   xxx    xxxxx",
    "!!!!!!!!!!!!!!!|!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                                                                  ",
    "                                           o                     o                                                ",
    "                    $                     x  x                 x  x                                       *       ",
    "                   xxx                   x    x       #       x    x                                     xxx      ",
    "                                        x      x             x      x                                             ",
    "         o                     yyyyy   x        x  yyyvyyy  x        x    yyyyy                                   ",
    "                             y!!!v!!!y            y!!!v!!!y             y!!!v!!!y                                 ",
    "         x                  y!       !y          y         y           y         y                    x           ",
    "                x           y         y          y         y           y         y             x                  ",
    "                             y   o   y     o      y      xy      o      y   o   y                                 ",
    "                              y     y              y     y               y    xy                                  ",
    "                             y                                                  y                                 ",
    "                            y              x          o          x               y                                ",
    "                   x        y    o    xy        y           y         y     o     y        x                      ",
    "                             y       y           yx        y           y         y                                ",
    "                              yx    y      #      y       y      #      yx      y                                 ",
    "                             y       y           y         y           y         y                                ",
    "                            y         y    x    y           y    x    y           y                               ",
    "                           y           y!!!!!!!y             y!!!!!!!y             y                              ",
    "                          y      o  x   y!!!!!y       x       y!!!!!y       o   x   y                             ",
    "                         yx              y!!!y                 y!!!y                 y                            ",
    "                        y                 y!y        o          y!y  x                y                           ",
    "                       y         #         y                     y          #          y                          ",
    "                      y                                                                 y                         ",
    "                               xxxxx             xx      xx               xxxxx                               o   ",
    "                              x     x              x!!!!x                x     x                                  ",
    "     @       x                                      xxxx                                         x                ",
    "     x                                                                                                        x   ",
    "          =        x          =            x           =         x         =             x          =             ",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                     x                                                        ",
   "                                                    x!x                                                       ",
   "                                                   x!|!x                                                      ",
   "                                                                                                              ",
   "                                                     o                                                        ",
   "                                              xxx y  y  y xxx                                                 ",
   "                                               x!!!!!!!!!!!x                                                  ",
   "                                              x!!|!!!!!!!|!!x                                                 ",
   "                                             x       o       x                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                      o   x          x          x    o                                        ",
   "                                         x!!!!!!!!!!!!!!!!!!!!!!!x                                            ",
   "                                   y    x                         x     y                                     ",
   "                                    y                o                 y                                      ",
   "                                     y        x x          x x        y                                       ",
   "                                      y     x!!!!!x      x!!!!!x     y                                        ",
   "                                       y   x!!!!!!!x    x!!!!!!!x   y                                         ",
   "                                            x!!!!!x      x!!!!!x                                              ",
   "                                             x!v!x   o    x!v!x                                               ",
   "     @                                                                                                        ",
   "     x                                                                                          x             ",
   "                                                 x       x                                                    ",
   "                                                  x!!x!!x                             x                       ",
   "                                                   x!!!x                                                      ",
   "                                  y                =x x=                y                                     ",
   "                            x     yy   yyyyyyyy   yyyyxyy    yyyyyyy   yy    x                                ",
   "                                                   x!!!x                                                      ",
   "                       x                          x!!!!!x                                                     ",
   "                                            o    x!|!!!|!x   o                                                ",
   "                  x                             x         x                           x                       ",
   "         o                                           o     x                                                  ",
   "             x                                x                                                               ",
   "                                            yx               xy                                               ",
   "         x                                                                                      x             ",
   "                                                                                                              ",
   "                                                xx!!!!!!!xx                                                   ",
   "                                               x   x!!!x   x                                                  ",
   "                                    xxx             xxx             xxx                                       ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "       y   y                                                                                                  ",
   "        y y   yyy  y   y                                                                                      ",
   "         y   y   y y   y                                                                                      ",
   "         y   y   y y   y                                                                                      ",
   "         y    yyy   yyy                                                                                       ",
   "                            y                                                                                 ",
   "     y     y  yyyyy  y   y  y                                                                                 ",
   "     y  y  y    y    yy  y  y                                                                                 ",
   "     y y y y    y    y y y                                                                                    ",
   "      y   y   yyyyy  y  yy  y                                                                                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
